### ISSUE TITLE
Present at GISRUK 2022

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/presentations#5]

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/161987006-e5783db3-e3db-402b-9641-dc4aeb1d01d7.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/161992916-2d1dfea6-e783-4b2d-b6b8-61522f38ad8e.png)

**Comment by Robinlovelace** [comment]
Heads-up @temospena @rogerbeecham and @dabreegster I'm presenting at ~16:30. Slides: https://www.robinlovelace.net/presentations/gisruk2022-jittering.html#1 see the gisruk2022-jittering.Rmd in this repo for source, any comments in next hour or so? Looking forward to it, sorry a bit late notice!

**Comment by temospena** [comment]
> ![image](https://user-images.githubusercontent.com/1825120/161992916-2d1dfea6-e783-4b2d-b6b8-61522f38ad8e.png)

red: origins, green: destinations? that's a nice one. very interesting to mention that if this is a "small" area, other methods would possible represent this OD trips as a single point (same O and D) in the center (or weighed centroid).
and jittering method gives the possibility to represent as diffuse as the image :slightly_smiling_face:

**Comment by Robinlovelace** [comment]
> red: origins, green: destinations?

Correct, although other way round! Could use this to test/validate jittering with different parameters.
